In [62]:
import numpy as np
arry1 =np.array([[64392, 31655], [32579, 0], [49248, 4626], [0, 0]] , dtype=np.uint16)
print("array shhape is", arry1.shape)
print("array dimension is", arry1.ndim)
print("array size is", arry1.size)

array shhape is (4, 2)
array dimension is 2
array size is 8


In [57]:
# Exercise 2: Create a 5X2 integer array from a range between 100
# to 200 such that the difference between each element is 10

import numpy as np

arry1 = np.arange(100,200,10)
arry1 = arry1.reshape(5,2)
print(arry1)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
# Exercise 3: Following is the provided numPy array. Return array
# of items by taking the third column from all rows

import numpy as np
sample_array = np.array([[11, 22,33], [44,55,66], [77,88,99]])
arry1 = sample_array[:,2:]
print(arry1)

[[33]
 [66]
 [99]]


In [ ]:
# Exercise 4: Return array of odd rows and even columns from
# below numpy array

import numpy as np
sample_array = np.array([[3,6,9,12], [15,18,21,24], [27,30,33,36], [39,42,45,48], [51,54,57,60]])
arry1 = sample_array[0::2,1::2]
print(arry1)


[[ 6 12]
 [30 36]
 [54 60]]


In [37]:
# Exercise 5: Create a result array by adding the following two
# NumPy arrays. Next, modify the result array by calculating the
# square of each element

import numpy as np
array1 = np.array([[5,6,9], [21 ,18, 27]])
array2 = np.array([[15,33,24], [4,7,1]])
array = array1+ array2
print(array)
array = array**2
print(array)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


In [56]:
import numpy as np
array1 = np.arange(10,34).reshape(8,3)
print(array1)
array2 = np.split(array1,4,axis=0)
print(array2)


[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [1]:
import numpy as np
array1 = np.array([[34,43,73],[82,22,12],[53,94,66]])

arr = np.argsort(array1[1])
array2 = array1[:,arr]
print(array2)

arr1 = np.argsort(array1[:,1])
array1 = array1[arr1,:]
print(array1)

[[73 43 34]
 [12 22 82]
 [66 94 53]]
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [6]:
import numpy as np
array1 = np.array([[34,43,73],[82,22,12],[53,94,66]])
array2 = array1.max(axis=0)
print(array2)
array3 =array1.min(axis=1)
print(array3)


[82 94 73]
[34 12 53]


In [1]:
#q9

import numpy as np
array1 = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
arr_new = np.delete(array1, 1, axis=1)
print(arr_new)
arr_new[:,1]= newColumn
print(arr_new)
array1[:,1] = newColumn
print(array1)


[[34 73]
 [82 12]
 [53 66]]
[[34 10]
 [82 10]
 [53 10]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [ ]:
#q10

import numpy as np
array1 = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
arr_new = np.delete(array1, 1, axis=1)
print(arr_new)
arr_new[:,1]= newColumn
print(arr_new)
array1[:,1] = newColumn
print(array1)


In [108]:
def unique_list(list1):
    list2 =[]
    list3 = []
    for i in list1:
        if not str(i).isdigit():
            return "TypeError" 
        elif i not in list2:
             list2.append(i)
        else:
            list3.append(i)
    return list2,list3


n = int(input("Enter number of elements: "))
user_list = [(input(f"Enter number {i+1}: ")) for i in range(n)]
print(user_list)
print(unique_list(user_list))


['1233', '2', '2', '2', '3', '4']
(['1233', '2', '3', '4'], ['2', '2'])
